services:
  postgres:
    image: postgres:16-alpine
    container_name: clarity-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-clarity_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clarity-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-clarity_db} -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  flyway: # --- Added Flyway Service ---
    image: flyway/flyway:10.17.0
    container_name: clarity-flyway-migration
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-clarity_db}
      FLYWAY_USER: ${POSTGRES_USER:-postgres}
      FLYWAY_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      # Mount your migration scripts to the location specified in flyway.conf
      - ./db/migration:/flyway/sql:ro
      # Mount your config file
      - ./db/flyway/flyway.conf:/flyway/conf/flyway.conf:ro
    # Command tells Flyway to use the config file and run migrate
    command: ["-configFiles=/flyway/conf/flyway.conf", "migrate"]
    networks:
      - clarity-network
    depends_on:
      postgres:
        # Wait for postgres to be healthy before running migrations
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clarity-backend
    restart: unless-stopped
    depends_on:
      flyway: # Depends on flyway now, not directly on postgres
        # Wait for migrations to complete successfully
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # PostgreSQL connection settings
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-clarity_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-86400000}
      JWT_KID: ${JWT_KID:-646b2b4576e3e06abfcee95c8e7d19f2}
      # Disable Hibernate auto DDL, using Flyway instead
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      # CORS settings
      CORS_ALLOWED_ORIGINS: http://localhost:3000,http://localhost:5173,http://localhost:80,http://localhost,http://frontend,http://clarity-frontend
    networks:
      - clarity-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: clarity-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:8080}
    networks:
      - clarity-network

volumes:
  postgres_data:

networks:
  clarity-network:
    driver: bridge 