services:
  postgres:
    image: postgres:16-alpine
    container_name: clarity-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clarity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - clarity-network

volumes:
  postgres_data_dev:

networks:
  clarity-network:
    driver: bridge 