services:
  postgres:
    image: postgres:16-alpine
    container_name: clarity-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: clarity_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - clarity-network

  # Add pgAdmin for easier database management during development
  pgadmin:
    image: dpage/pgadmin4
    container_name: clarity-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - clarity-network

volumes:
  postgres_data_dev:

networks:
  clarity-network:
    driver: bridge 