version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: clarity-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-clarity_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - clarity-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: clarity-backend
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-clarity_db}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-default_jwt_secret_key_for_development_only}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-86400000}
    networks:
      - clarity-network

volumes:
  postgres_data:

networks:
  clarity-network:
    driver: bridge 