spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    azure:
      passwordless-enabled: true
      credential:
        managed-identity-enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# JWT configuration
jwt:
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}
  rsa:
    private-key: ${JWT_RSA_PRIVATE_KEY:}
    public-key: ${JWT_RSA_PUBLIC_KEY:}
    private-key-file: ${JWT_RSA_PRIVATE_KEY_FILE:}
    public-key-file: ${JWT_RSA_PUBLIC_KEY_FILE:}
  kid: ${JWT_KID:}

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQL: WARN
    com.aifinancial.clarity.poc: INFO
    com.zaxxer.hikari: DEBUG
    com.azure.identity: DEBUG
    com.azure.identity.extensions: DEBUG
    org.postgresql.jdbc: DEBUG

# H2 Console (建議 staging 關閉，留著可手動切換)
h2:
  console:
    enabled: false
