spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clarity_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

# JWT configuration
jwt:
  secret: ${JWT_SECRET:TjwkViUOags3v+vFi6sns5Ji+otqLDtO7Wog0D5L4Lj5Gt7bmZ1T4Uee6b+E2Md+kdQF9HGPdejlLEvqkixBDg==}
  expiration-ms: ${JWT_EXPIRATION_MS:86400000}  # 24 hours

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Logging
logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    com.aifinancial.clarity.poc: DEBUG

# H2 Console
h2:
  console:
    enabled: true
    path: /h2-console 