name: Backend Docker Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Docker image tag to use'
        required: true

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      IMAGE_NAME: backend
      IMAGE_TAG: ${{ github.event_name == 'workflow_dispatch' && inputs.imageTag || github.ref_name }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B clean package -DskipTests
      
      - name: Docker Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
            login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
            username: ${{ env.REGISTRY_USERNAME }}
            password: ${{ env.REGISTRY_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest 