name: Backend CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B clean package -DskipTests

      - name: Run tests
        run: ./mvnw -B test 

  build-and-push-docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    defaults:
      run:
        working-directory: ./backend
    
    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.AZURE_REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      IMAGE_NAME: backend
      IMAGE_TAG: ${{ github.sha }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw -B clean package -DskipTests
      
      - name: Docker Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
            login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
            username: ${{ env.REGISTRY_USERNAME }}
            password: ${{ env.REGISTRY_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest 